name: PHP Composer

on: [push]

jobs:
  build:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v1

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
      
    - name: Install dependencies
      run: npm install

    - name: Build
      run: npx webpack -p
            
    - name: Release
      run: |
        mkdir -p acf-image-aspect-ratio-crop
        cp -r *.php *.md readme.txt assets fields vendor composer.json composer.lock acf-image-aspect-ratio-crop
        zip -r acf-image-aspect-ratio-crop.zip acf-image-aspect-ratio-crop
      
    - uses: actions/upload-artifact@master
      with:
        name: acf-image-aspect-ratio-crop.zip
        path: acf-image-aspect-ratio-crop.zip
      
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: acf-image-aspect-ratio.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
